repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
  - id: shellcheck
    exclude: ^microsoft-office-unlicense-tool
  - id: shfmt
    args: [-i 2]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-json
  - id: check-yaml
  - id: check-xml
  - id: pretty-format-json
    args: [--autofix]
  - id: check-executables-have-shebangs
  - id: detect-private-key
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/homebysix/pre-commit-macadmin
  rev: v1.11.0
  hooks:
  - id: check-autopkg-recipe-list
  - id: check-autopkg-recipes
  - id: forbid-autopkg-overrides
  - id: forbid-autopkg-trust-info
  - id: check-plists